### CLEANUP ###
# Debian, Ubuntu

# about 400MB on an Ubuntu image - @jarno https://askubuntu.com/a/620515/831854
- name: Register previous kernel versions to be removed.
  shell: dpkg-query -W -f'${Package}\n' 'linux-*' | sed -nr 's/.*-([0-9]+(\.[0-9]+){2}-[^-]+).*/\1 &/p' | sort -k 1,1V | awk '($1==c){exit} {print $2}' c=$(uname -r | cut -f1,2 -d-)
  register: old_kernel_packages
  changed_when: false

- name: Remove packages of previous kernel versions.
  apt:
    name: "{{ old_kernel_packages.stdout }}"
    state: absent
    purge: yes
    autoremove: yes

- name: Copy the cleanup script.
  template:
    src: template-cleanup-debian-ubuntu.sh.j2
    dest: /usr/local/bin/template-cleanup.sh
    mode: a+x

- name: Run the cleanup script for VM templates (only once).
  shell: /usr/local/bin/template-cleanup.sh
  args:
    creates: /etc/.template-cleanup.done
