### Initial Setup ###
# OpenBSD

- name: KICKSTART - OpenBSD.
  block:
  ### SUDOERS ###
  # TODO check that creating a new user works as expected
  # - name: Ensure group "{{ iserver_user }}" exists
  #   group:
  #     name: "{{ iserver_user }}"
  #     state: present
  #
  # - name: Ensure that the default user "{{ iserver_user }}" exists
  #   user:
  #     name: "{{ iserver_user }}"
  #     group: "{{ iserver_user }}"
  #     password: '*'

  - name: Check if iserver_user exists.
    shell: id -u "{{ iserver_user }}" > /dev/null 2>&1
    ignore_errors: True
    changed_when: false
    register: user_exists

  - name: Add the default user with passwordless doas.
    template:
      src: doas-openbsd.conf.j2
      dest: /etc/doas.conf
      mode: 0440
    when: user_exists is succeeded
  ## End of block KICKSTART
  become: true
  become_method: "{{ iserver_kickstart_become }}"
  tags:
    - vanilla

- name: Reset SSH connection to allow user changes to affect 'current login user'.
  meta: reset_connection
  tags:
    - vanilla

## Now that the default user can do passwordless doas, run the rest with doas.
- name: MAIN
  block:
  ### BASE PACKAGES ###
  - name: Base Packages - OpenBSD
    import_tasks: packages-openbsd.yml

  - name: Create symbolic links for python 3
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
      - { src: '/usr/local/bin/python3', dest: '/usr/bin/python' }
      - { src: '/usr/local/bin/python3', dest: '/usr/local/bin/python' }
      - { src: '/usr/local/bin/python3-config', dest: '/usr/local/bin/python-config' }
      - { src: '/usr/local/bin/pydoc3', dest: '/usr/local/bin/pydoc' }

  ### NETWORKING ###
  - name: New SSH host keys on first boot.
    import_tasks: ssh-host-keygen-openbsd.yml
    # only run when is_template tag is specifically requested
    tags:
      - never
      - is_template

  - name: Set hostname.
    hostname:
      name: "{{ iserver_hostname }}"
    notify:
      - Apply Network Settings
    tags:
      - vanilla

  - name: Ensure that DHCP or static IP is configured.
    import_tasks: networking-openbsd.yml

  - name: Copy original hosts file to back it up (once).
    command: cp /etc/hosts /etc/hosts.original
    args:
      creates: /etc/hosts.original
    tags:
      - vanilla

  - name: Create new hosts file.
    template:
      src: hosts.j2
      dest: /etc/hosts
    notify:
      - Apply Network Settings
    tags:
      - vanilla

  ### SSH ###
  - name: Ensure that the default user has a SSH authorized key.
    authorized_key:
      user: "{{ iserver_user }}"
      state: present
      key: "{{ iserver_sshkey }}"
    tags:
      - vanilla

  #'UseDNS no' avoids login delays when the remote client's DNS cannot be resolved
  - name: Apply SSHD configuration.
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^#?\s*{{ item.key }}\s'
      line:   '{{ item.key }} {{ item.value }}'
      validate: '/usr/sbin/sshd -t -f %s'
    with_items:
    - key:   "PermitRootLogin"
      value: "no"
    - key:   "PasswordAuthentication"
      value: "no"
    - key:   "ChallengeResponseAuthentication"
      value: "no"
    - key:   "UseDNS"
      value: "no"
    - key:   "Banner"
      value: "{{ iserver_ssh_banner }}"
    - key:   "Port"
      value: "{{ iserver_ssh_port }}"
    notify: Restart SSHD
    tags:
      - vanilla

  - name: Add a warning banner, shown before SSH login.
    copy:
      src: issue.net
      dest: "{{ iserver_ssh_banner }}"
    when: iserver_ssh_banner != "none"

  ### CUSTOMIZE ###
  - name: Timezone.
    import_tasks: timezone-most-distros.yml
    tags:
      - vanilla

  - name: Customize.
    import_tasks: customize-openbsd.yml

  ### CLOUD ###
  - name: Serial Console.
    import_tasks: serialconsole-openbsd.yml
    tags:
      - vanilla

  # TODO GROW PARTITION
  # - name: Grow Partition Automatically.
  #   import_tasks: growpartition-openbsd.yml

  - name: Patch OpenBSD with latest fixes.
    command: syspatch
    changed_when: false
    tags:
      - vanilla

  ### CLEANUP ###
  - name: Cleanup.
    import_tasks: cleanup-openbsd.yml
    # only runs when the is_template tag is specifically requested
    tags:
      - never
      - is_template

  - name: Lock root account to prevent logins for root from console.
    user:
      name: root
      # or use '*'
      password: '!'
    when: iserver_lock_root
    tags:
      - vanilla

  # End of block MAIN
  become: true
  become_method: "{{ iserver_become }}"
