---

- name: Enable Epel
  yum:
    name: epel-release
    state: present
  when: iserver_centos_enable_epel

- name: Update Yum packages
  yum:
    name: '*'
    state: latest


- name: Ensure that initial packages are installed.
  yum:
    name: "{{ iserver_rpm_packages }}"
    state: present
